name: dl2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - torch==2.4.0
    - torchvision==0.19.0
    - torchaudio==2.4.0
    - git+https://github.com/openai/CLIP.git
    - numpy>=1.26.4
    - pillow
    - einops
    - typed-argument-parser
    - tqdm
    - transformers
    - absl-py
    - matplotlib
    - scipy
    - tensorboard
    - opencv-python
    - blosc
    - setuptools>=57.5.0
    - beautifulsoup4
    - bleach
    - defusedxml
    - jinja2>=3.0
    - jupyter-core>=4.7.0
    - jupyterlab-pygments
    - mistune
    - nbclient>=0.5.0
    - nbformat>=5.7
    - pandocfilters>=1.4.1
    - tinycss2
    - traitlets>=5.1
